### ISSUE TITLE
tensor dataset

### ISSUE THREAD

**Issue by jelewis** [skeydan/Deep-Learning-and-Scientific-Computing-with-R-torch#4]
the package modeldata no longer has the dataset "okc" used in the book chapter Tensors

**Comment by skeydan** [comment]
Thanks @jelewis for reporting! You're right, evidently it was removed in version 1.0.1 for privacy concerns (see https://github.com/tidymodels/modeldata/blob/main/NEWS.md).

The reason I originally picked it was that it had a big range of data types, and so seemed a perfect fit for https://skeydan.github.io/Deep-Learning-and-Scientific-Computing-with-R-torch/tensors.html#tensors-from-datasets (which is all about how to approach different data types).
I hope that the ideas outlined still are useful, since they should generalize to other datasets :-)
